[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.2.0"
authors = ["nekitdev <nekit@nekit.dev>"]
rust-version = "1.95"
edition = "2024"
repository = "https://github.com/nekitdev/graphs"
license = "MIT"

[workspace.dependencies.bon]
version = "3.9.1"
default-features = false

[workspace.dependencies.pest]
version = "2.8.6"
default-features = false

[workspace.dependencies.pest_derive]
version = "2.8.6"
default-features = false

[workspace.dependencies.non-empty-slice]
version = "0.6.0"
default-features = false

[workspace.dependencies.ownership]
version = "0.3.0"

[workspace.dependencies.proc-macro2]
version = "1.0.106"
default-features = false

[workspace.dependencies.quote]
version = "1.0.45"
default-features = false

[workspace.dependencies.syn]
version = "2.0.117"
default-features = false

[workspace.dependencies.indexmap]
version = "2.14.0"
default-features = false

[workspace.dependencies.serde]
version = "1.0.228"
default-features = false

[workspace.dependencies.thiserror]
version = "2.0.18"
default-features = false

[workspace.dependencies.trait-aliases]
version = "0.3.0"
default-features = false

[workspace.dependencies.graphs-assert]
path = "crates/graphs-assert"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-core]
path = "crates/graphs-core"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-common]
path = "crates/graphs-common"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-either]
path = "crates/graphs-either"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-acyclic]
path = "crates/graphs-acyclic"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-algorithms]
path = "crates/graphs-algorithms"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-bits]
path = "crates/graphs-bits"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-map]
path = "crates/graphs-map"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-simple]
path = "crates/graphs-simple"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-stable]
path = "crates/graphs-stable"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-traversal]
path = "crates/graphs-traversal"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-union-find]
path = "crates/graphs-union-find"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-dot]
path = "crates/graphs-dot"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-dot-parser]
path = "crates/graphs-dot-parser"
version = "0.2.0"
default-features = false

[workspace.dependencies.graphs-dot-macros]
path = "crates/graphs-dot-macros"
version = "0.2.0"
default-features = false

[package]
name = "graphs"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Graph data structures and algorithms."
documentation = "https://docs.rs/graphs"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["graph", "algorithm", "data-structure"]
categories = ["algorithms", "data-structures"]

[dependencies.graphs-core]
workspace = true

[dependencies.graphs-common]
workspace = true
optional = true

[dependencies.graphs-either]
workspace = true
optional = true

[dependencies.graphs-assert]
workspace = true
optional = true

[dependencies.graphs-acyclic]
workspace = true
optional = true

[dependencies.graphs-algorithms]
workspace = true
optional = true

[dependencies.graphs-bits]
workspace = true
optional = true

[dependencies.graphs-simple]
workspace = true
optional = true

[dependencies.graphs-stable]
workspace = true
optional = true

[dependencies.graphs-map]
workspace = true
optional = true

[dependencies.graphs-traversal]
workspace = true
optional = true

[dependencies.graphs-union-find]
workspace = true
optional = true

[dependencies.graphs-dot]
workspace = true
optional = true

[features]
default = [
    "std",
    "common",
    "either",
    "simple",
    "algorithms",
    "union-find",
    "dot",
    "dot-macros",
]
std = [
    "graphs-acyclic?/std",
    "graphs-algorithms?/std",
    "graphs-bits?/std",
    "graphs-common?/std",
    "graphs-core/std",
    "graphs-dot?/std",
    "graphs-either?/std",
    "graphs-map?/std",
    "graphs-map?/std",
    "graphs-simple?/std",
    "graphs-stable?/std",
    "graphs-traversal?/std",
    "graphs-union-find?/std",
]
common = ["dep:graphs-common"]
either = ["dep:graphs-either"]
assert = ["dep:graphs-assert"]
algorithms = ["dep:graphs-algorithms"]
acyclic = ["dep:graphs-acyclic"]
bits = ["dep:graphs-bits"]
simple = ["dep:graphs-simple"]
stable = ["dep:graphs-stable"]
map = ["dep:graphs-map"]
traversal = ["dep:graphs-traversal"]
union-find = ["dep:graphs-union-find"]
dot = ["dep:graphs-dot"]
dot-macros = ["graphs-dot?/macros"]
serde = ["graphs-core/serde", "graphs-common?/serde", "graphs-either?/serde"]

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "docsrs"]
