[package]
name = "graphs-core"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Core functionality for graphs."
documentation = "https://docs.rs/graphs-core"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["graph", "core"]

[dependencies.serde]
workspace = true
optional = true

[dependencies.bon]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.trait-aliases]
workspace = true

[dependencies.graphs-either]
workspace = true

[features]
# TODO: add "std" here
default = ["serde"]
serde = ["dep:serde"]
std = ["serde?/std"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
