//! The core prelude.

#[doc(inline)]
pub use crate::{
    algorithms::{Algorithm, Apply},
    attached::{DirectedEdges, Edges},
    base::{
        AllowLoop, Base, Directed, ForbidLoop, Looped, Multi, MultipleType, Pseudo, Simple,
        SingleType, Undirected,
    },
    build::{
        AddEdges, AddNodes, Build, RecoverableEdge, RecoverableNode, TryAddEdges, TryAddNodes,
        TryBuild,
    },
    by::By,
    capacity::{Capacities, Capacity, CapacityMethod, EdgeCapacity, NodeCapacity},
    cardinality::{Cardinality, Count, CountMethods, Order, Size},
    clear::{Clear, ClearEdges},
    connections::{
        Connection, DirectedConnection, DirectedConnectionMethods, Parts, ReverseConnection,
        UndirectedConnection, UndirectedConnectionMethods,
    },
    create::Create,
    data::{Data, DataMut, DataRef},
    degree::{Class, Degrees},
    direction::{Direction, Directional, Incoming, Outgoing},
    edges::{Edge, EdgeIn},
    exhaust::Exhaust,
    extend::{
        Extend, ExtendEdges, ExtendIntoEdges, ExtendIntoNodes, ExtendIterEdges, ExtendIterNodes,
        ExtendNodes, TryExtend, TryExtendEdges, TryExtendIntoEdges, TryExtendIntoNodes,
        TryExtendIterEdges, TryExtendIterNodes, TryExtendNodes,
    },
    find::{Find, Found, Missing, Nothing, OrNothing},
    freeze::Freeze,
    frozen::Frozen,
    id::{DefaultUntypedId, EdgeTypeId, Id, NodeTypeId, UntypedId},
    identifiers::{EdgeIdentifiers, Identifiers, NodeIdentifiers},
    index::{DefaultUntypedIndex, EdgeTypeIndex, Index, NodeTypeIndex, UntypedIndex},
    indexed::{Compact, EdgeCompact, EdgeIndexed, Indexed, NodeCompact, NodeIndexed},
    kinds::{DefaultKind, Directed as DirectedKind, Kind, Undirected as UndirectedKind},
    loops::{Allow, Forbid, Loop},
    map::{EdgeMap, EdgeMapIn, Identity, Map, NodeMap, NodeMapIn},
    neighbors::{DirectedNeighbors, Neighbors},
    nodes::{Node, NodeIn},
    recoverable,
    recoverable::{Recoverable, RecoverableError},
    recoverable_error, recoverable_return,
    references::{
        DirectedEdgeRef, EdgeRef, EdgeRefIn, EdgeReferences, NamedEdgeRef, NamedNodeRef, NodeRef,
        NodeRefIn, NodeReferences, References, UndirectedEdgeRef, UnnamedEdgeRef, UnnamedNodeRef,
    },
    remove::{Remove, RemoveEdge, RemoveNode, Removed, RemovedIn},
    reserve::{Reserve, ReserveEdges, ReserveNodes},
    reverse::Reverse,
    sentinel::Sentinel,
    specs::Specs,
    subgraph::{EdgeFilter, Filter, NodeFilter, Subgraph},
    types::{DefaultType, Multiple, Single, Type},
    update::{RecoverableUpdated, Taken, TakenIn, TryUpdate, Update, Updated, UpdatedIn},
    visit::{Visit, Visitor},
    walk::{Walk, Walker},
};
