[package]
name = "graphs-acyclic"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Acyclic graph adapters."
documentation = "https://docs.rs/graphs-acyclic"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["graph", "acyclic"]

[dependencies.graphs-algorithms]
workspace = true

[dependencies.graphs-common]
workspace = true

[dependencies.graphs-core]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.trait-aliases]
workspace = true

[features]
# TODO: add "std" here
default = []
std = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
