[package]
name = "graphs-dot"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Implementation of the DOT language."
documentation = "https://docs.rs/graphs-dot"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["graph", "dot"]

[dependencies.graphs-dot-macros]
workspace = true
optional = true

[dependencies.graphs-dot-parser]
workspace = true

[dependencies.graphs-core]
workspace = true

[features]
default = ["std", "macros"]
std = ["graphs-dot-parser/std"]
macros = ["graphs-dot-macros"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
