[package]
name = "graphs-dot-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Macros for embedding DOT graphs."
documentation = "https://docs.rs/graphs-dot-macros"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["graph", "dot", "macro"]

[lib]
proc-macro = true

[dependencies.graphs-dot-parser]
workspace = true
features = ["std", "proc-macro"]

[dependencies.proc-macro2]
workspace = true
features = ["proc-macro"]

[dependencies.quote]
workspace = true
features = ["proc-macro"]

[dependencies.syn]
workspace = true
features = ["parsing", "printing", "proc-macro"]
